# Generated by Django 5.2.6 on 2025-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('ev', models.IntegerField()),
                ('het', models.IntegerField()),
            ],
            options={
                'verbose_name': 'huzas',
                'verbose_name_plural': 'huzasok',
            },
        ),
    ]
