# Generated by Django 5.2.6 on 2025-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huzott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('huzasid', models.IntegerField()),
                ('szam', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Huzott',
                'verbose_name_plural': 'Huzottak',
            },
        ),
        migrations.CreateModel(
            name='Nyeremeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('huzasid', models.IntegerField()),
                ('talalat', models.IntegerField()),
                ('darab', models.IntegerField()),
                ('ertek', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nyeremeny',
                'verbose_name_plural': 'Nyeremenyek',
            },
        ),
    ]
